# Generated by Django 4.0.3 on 2022-03-13 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='address1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='address2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='zipcode',
            field=models.CharField(default='', max_length=9, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
