# Generated by Django 4.0.3 on 2022-03-13 23:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_address1_useraccount_address2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='state',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='zipcode',
        ),
        migrations.CreateModel(
            name='ClientInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=50)),
                ('address1', models.CharField(default='', max_length=100)),
                ('address2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=2)),
                ('zipcode', models.CharField(default='', max_length=9, validators=[django.core.validators.MinLengthValidator(4)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
